apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: daemonset-infra-prod
  namespace: default
  labels:
    k8s-app: daemonset-infra-prod
spec:
  selector:
    matchLabels:
      name: daemonset-infra-prod
  template:
    metadata:
      labels:
        name: daemonset-infra-prod
    spec:
      containers:
      - name: daemonset-infra-prod
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; sleep 1000
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
      nodeSelector: 
        infra: "production"
